spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: p@$$w0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate :
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgres
