spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: job
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate :
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgres
