name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy JwtSpringBootAuthentication
    runs-on: ubuntu-latest

    services:
      postgresdb:
        image: postgres
        env:
          POSTGRES_USER: job
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      command: postgres -D /data/postgres -c 'config_file=/etc/postgresql/postgresql.conf' -d
#      pgadmin:
#        image: dpage/pgadmin4
#        env:
#          PGADMIN_DEFAULT_EMAIL: jbgwese@gmail.com
#          PGADMIN_DEFAULT_PASSWORD: password
#          PGADMIN_CONFIG_SERVER_MODE: 'False'
#        volumes:
#          - pgadmin:/var/lib/pgadmin
#
#        ports:
#          - 5050/tcp
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

#      - name: Set up PostgreSQL
#        run: |
#          docker pull postgres:latest
#          docker run --name  -e POSTGRES_USER=job -e POSTGRES_PASSWORD=password -p 5432 -d postgres


      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/JwtSpringBootAuthentication:today
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/JwtSpringBootAuthentication:today